from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class Runtime(Protocol):
    """Execution backend the dispatcher task layer depends on.

    Implemented by ContainerManager (Docker) and LocalRuntime (host subprocess).
    """

    def ensure_running(self, project_id: str) -> str: ...
    def container_name(self, project_id: str) -> str: ...
    def build_exec_process(self, name: str, env: dict[str, str], command: list[str],
                           timeout_seconds: int | None = None, kill_after_seconds: int = 5): ...
    def write_text_file(self, name: str, path: str, content: str) -> None: ...
    def install_skills(self, workspace_key: str, skill_dirs: list) -> None: ...
    def snapshot_root(self) -> str: ...
    def create_startup_container(self) -> str: ...
    def needs_completed_cleanup(self, project_id: str) -> bool: ...
    def needs_stopped_cleanup(self, project_id: str) -> bool: ...
    def cleanup_completed(self, project_id: str) -> bool: ...
    def cleanup_stopped(self, project_id: str) -> bool: ...
    def close(self) -> None: ...
